### PR TITLE
Bug fix in ndim integration and added project file

### PR DESCRIPTION
**Pull request by m-wells**
My tests were failing with ndim integration.  They were returning `nothing`.  The tests now pass for me.  I also added a `Project.toml` file.

### CODE REVIEW

**Comment by m-wells** [comment]
This should address the issue raised in #16

**Comment by m-wells** [comment]
Also by using a functional barrier technique I am able to reduce allocations.  Compare the previous working method
```
julia> x,y = (1:10,1:9,1:8), rand(10,9,8);

julia> @time integrate(x, y)
  0.001067 seconds (560 allocations: 21.359 KiB)
256.89755162643917
```
with
```
julia> @time integrate(x, y)
  0.000130 seconds (298 allocations: 12.031 KiB)
256.89755162643917
```

**Comment by m-wells** [comment]
@dextorious if we can merge this in soon that would be appreciated as several of my packages use this as a dependency :)

**Comment by dextorious** [comment]
Sorry, I've been on vacation. The reason your tests were failing is the fact that we're using positional arguments for everything and haven't been perfectly consistent with the ordering. In current Julia we would use keyword arguments and avoid that issue, but fixing it now would be a very breaking change.

I would have preferred to keep the cache, but after quickly playing around with the code I didn't find a way to make the compiler emit sensible code without too much effort. So, I'm merging your code to get something that works and is reasonably fast, but I'll probably consider a breaking rewrite in the future (hopefully with a fallback of a backwards compatible API).

**Comment by m-wells** [comment]
I can submit a n-dimensional memory efficient method for `TrapezoidalFast`.  It wouldn't be extendable to any other methods however.

**Comment by dextorious** [comment]
`TrapezoidalFast` (and `TrapezoidalEvenFast` as a special case) should already cover most of the common usecases.

**Pull request merged**
