### PR TITLE
replace 0.5 by 1//2

### PR DESCRIPTION
**Pull request by jw3126**
#9

### CODE REVIEW

**Comment by jishnub** [comment]
Does the value being a rational help over a float? `0.5` may be stored exactly as a float.

**Comment by jw3126** [comment]
I think so, you can run the tests and see what happens, when you change to `0.5`.

**Comment by jw3126** [comment]
The point is that `0.5` "poisons" e.g. `Float32` values, while `1//2` does not.

**Comment by jishnub** [comment]
You're right, the rational value gets promoted to the appropriate floating point type in multiplications. The performance difference appears negligible.

**Pull request merged**
